services:
  - type: web
    name: wadi-api
    env: node
    plan: free
    region: oregon
    buildCommand: pnpm install && pnpm --filter wadi-api build
    startCommand: node apps/api/dist/index.js
    envVars:
      - key: IS_RENDER
        value: true
      - key: PORT
        value: 10000
