version: '3.8'

services:
  # Base de Datos para el "Iron Core"
  postgres:
    image: postgres:15
    container_name: wadi-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wadi
    ports:
      - "5432:5432"

  # Motor para la cola de tareas (BullMQ)
  redis:
    image: redis:alpine
    container_name: wadi-redis
    restart: always
    ports:
      - "6379:6379"
